### ISSUE TITLE
Cannot open timeshift from desktop

### ISSUE THREAD

**Issue by wzh4464** [linuxmint/timeshift#219] opened 2023-07-29 09:47 UTC
**Describe the bug**
Usually, we click the icon for `timeshift-laucher` and it will prompt to require password of sudo. But days after I click the icon and nothing happened. I input `timeshift-laucher` in terminal and I get `Error checking for authorization in.teejeetech.pkexec.timeshift-gtk: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`.

Use `sudo` is temporarily good but I think it may still have problems.

**To Reproduce**
1. Click on `Timeshift` icon:
3. Nothing happens
**Expected behavior**
Promopt a password input window.

**System:**
 - Ubuntu 22.04
 - Desktop Cinnamon
 - v21.09.1

**Comment by leigh123linux** [comment] 2023-07-29 10:38
Duplicate of https://github.com/linuxmint/timeshift/issues/147

**Closed as completed by leigh123linux** 2023-07-29 10:38 UTC

**Comment by wzh4464** [comment] 2023-07-30 04:11
Can I open it again? Since I changed it to cinnamon desktop system and still get `Error checking for authorization in.teejeetech.pkexec.timeshift-gtk: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
`, which is different from #147.

**Comment by leigh123linux** [comment] 2023-07-30 11:51
Does this fail?, run as non-root

```
pkexec nemo
```

**Comment by wzh4464** [comment] 2023-07-30 15:36
Yes, this fails too.
```
$pkexec nemo
Error checking for authorization org.nemo.root: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by leigh123linux** [comment] 2023-07-30 18:51
Your issue is caused by broken polkit package, file the issue at ubuntu bug tracker

**Comment by wzh4464** [comment] 2023-07-30 23:55
Right.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Leigh Scott ***@***.***>
发送时间: Monday, July 31, 2023 2:51:54 AM
收件人: linuxmint/timeshift ***@***.***>
抄送: Harry Wu ***@***.***>; Author ***@***.***>
主题: Re: [linuxmint/timeshift] Cannot open timeshift from desktop (Issue #219)


Your issue is caused by broken polkit package, file the issue at ubuntu bug tracker

―
