### ISSUE TITLE
Are you shure?

### ISSUE THREAD

**Issue by GaVenga** [linuxmint/timeshift#59] opened 2022-08-19 10:05 UTC
If you klick "delete" - it will be done without asking like: "are you really really shure"

**Comment by melizasw** [comment] 2022-08-22 06:33
Duplicate of #38 ?

**Comment by jjroysdon** [comment] 2022-08-25 01:02
Dupe of #18

**Comment by clefebvre** [comment] 2022-09-28 10:58
Closed as duplicate.

**Closed as completed by clefebvre** 2022-09-28 10:58 UTC
