### ISSUE TITLE
Crash during snapshot creation first thing after Ubuntu upgrade 22.04 LTS -> 22.10

### ISSUE THREAD

**Issue by Tom-H-L** [linuxmint/timeshift#91] opened 2022-11-05 17:32 UTC
**Describe the bug**
The app closes without any further notification during creating the first snapshot after booting up the newly upgraded system (Ubuntu 22.04 LTS -> 22.10).

**To Reproduce**
Boot up, enforce manual snapshot from a profile, and it will crash again during snapping. Worked like a charm prior the upgrade.

**System:**
 - Ubuntu 22.10 64bit
 - Gnome
 - Timeshift v22.06.5

The folder for the new snapshot gets created but it is not listed in the app after restarting it. I manually deleted the folder on the file system. Was that a good idea?

**Comment by cimarronline** [comment] 2022-11-06 18:54
The issue has been fixed by the original creator of Timeshift, but the Mint maintainers have not included the fix yet (the current version of Mint is not affected by this issue, since it is caused by the update of glib2 to version 2.74): https://github.com/linuxmint/timeshift/issues/69#issuecomment-1279793417

Using Timeshift in the terminal should still work. Just the GUI is affected.

**Comment by dm2912** [comment] 2022-11-12 20:59
Its not restricted to creation

It crashes on restore as well.

**Comment by cimarronline** [comment] 2022-11-13 16:13
A new version has been released with the fixes: https://github.com/linuxmint/timeshift/releases

The .deb packages are in packages.tar.gz

**Comment by mcarans** [comment] 2022-11-22 03:05
Does anyone know how to get the fixed version to be included in an Ubuntu PPA?

edit: I've submitted a bug here: https://bugs.launchpad.net/ubuntu/+source/timeshift/+bug/1997334

**Comment by mcarans** [comment] 2022-11-24 02:26
I realised that Ubuntu takes its package from Debian so have submiited a bug here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024733

**Comment by mtwebster** [comment] 2022-11-24 05:14
The daily builds ppa has the latest version for 20.04, 22.04, 22.10, 23.04:
https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds

Or, as mentioned, you can try the builds here:
https://github.com/linuxmint/timeshift/releases/tag/master.mint21

**Closed as completed** 2022-11-26 18:05 UTC
